# Generated by Django 4.2.3 on 2023-07-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('url', models.URLField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('rating', models.FloatField()),
                ('no_of_reviews', models.IntegerField()),
            ],
        ),
    ]
